### ISSUE TITLE
turn it into an npm package?

### ISSUE THREAD

**Issue by tnrich** [gizur/github-issues-export#12]
Could be a nice way for users to consume this resource.

**Comment by tnrich** [comment]
err sorry bout that. just found the package: https://www.npmjs.com/package/github-issues-export

npm search was no help at all...

**Comment by tnrich** [comment]
Hmm.. not quite sure how to use it from npm. I tried: 

`npm i -g github-issues-export` 

to no avail..

**Comment by colmsjo** [comment]
probably a node version problem
